# =============================================================================
# BASE CONFIGURATION
# =============================================================================

version: "3.7"

# =============================================================================
# SERVICES
# =============================================================================

services:

# =============================================================================
# BACKEND
# =============================================================================

  backend:
    container_name: ${CONTAINER_BACKEND_NAME}
    env_file: ./.env
    build:
      context: ./code
      dockerfile: Dockerfile
    ports:
      - target: 3301
        published: 3301
        protocol: tcp
        mode: host
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "20"
    networks:
      - backend

# =============================================================================
# NETWORK
# =============================================================================

networks:
  backend:
